# Generated by Django 4.2.5 on 2023-09-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='capteurs',
            fields=[
                ('id_capteur', models.AutoField(primary_key=True, serialize=False)),
                ('nom_capteur', models.CharField(max_length=100)),
            ],
        ),
    ]
