# Generated by Django 4.2.6 on 2023-10-26 08:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='captor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('lattitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='survey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('temperature', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('battery_level', models.FloatField()),
                ('rssi', models.IntegerField(max_length=3)),
                ('date', models.DateField()),
                ('capteur_id', models.IntegerField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='alert',
            fields=[
                ('id_alert', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency', models.IntegerField(max_length=6)),
                ('type', models.CharField(max_length=45)),
                ('limit', models.CharField(max_length=45)),
                ('recipients', models.ManyToManyField(to='API.recipient')),
            ],
        ),
    ]
