# Generated by Django 4.2.6 on 2023-12-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
