# Generated by Django 4.2.6 on 2023-10-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_alert_frequency_alter_survey_capteur_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captor',
            name='lattitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='captor',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
