# Generated by Django 4.2.6 on 2023-12-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_sensor_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='humidity_inferior',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='humidity_superior',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='temperature_inferior',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='temperature_superior',
            field=models.FloatField(null=True),
        ),
    ]
