# Generated by Django 4.2.5 on 2023-10-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='capteur',
            fields=[
                ('id_capteur', models.AutoField(primary_key=True, serialize=False)),
                ('name_capteur', models.CharField(max_length=64)),
                ('name_capteur2', models.CharField(max_length=64)),
            ],
        ),
    ]
