# Generated by Django 4.2.5 on 2023-10-01 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capteur',
            name='name_capteur2',
        ),
    ]
