# Generated by Django 4.2.5 on 2023-10-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0003_capteur_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capteur',
            name='position',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
