# Generated by Django 4.2.5 on 2023-10-24 21:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0004_alter_capteur_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capteur',
            name='id_capteur',
        ),
        migrations.RemoveField(
            model_name='capteur',
            name='position',
        ),
        migrations.AddField(
            model_name='capteur',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='capteur',
            name='lattitudde',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='capteur',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='survey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('temperature', models.FloatField(null=True)),
                ('humidity', models.IntegerField(null=True)),
                ('battery_level', models.FloatField()),
                ('rssi', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('capteur_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webApp.capteur')),
            ],
        ),
    ]
