# Generated by Django 4.2.5 on 2023-10-24 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0005_remove_capteur_id_capteur_remove_capteur_position_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='capteur_id',
            new_name='capteur',
        ),
    ]
