# Generated by Django 4.2.5 on 2023-10-25 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0007_alter_survey_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='capteur',
            new_name='Captor',
        ),
        migrations.RenameField(
            model_name='captor',
            old_name='name_capteur',
            new_name='name',
        ),
    ]
